### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by hughjfchen** [seanhess/hyperbole#1]
Hi, I'm exploring some haskell web framework and come to this through haskell discourse. I'm really interested in this library, however, I cannot find any documents(quickstart guide, or tutorial) to get started. I have went through the `example` but it looks like the `client` directory must be included to use this library in my own project? Is that true? I really hope there could be some guide to how to use this library.

**Comment by seanhess** [comment]
Hey, you inspired me to get a release of this out! I’m busy writing documentation. Should be done early next week.

**Comment by seanhess** [comment]
Hey @hughjfchen, I've released [Hyperbole 0.3.5](https://hackage.haskell.org/package/hyperbole-0.3.5/docs/Web-Hyperbole.html). It's fully documented now. Give it shot and let me know if you get lost

**Comment by hughjfchen** [comment]
Wow, this is a huge improvement on documentation. Especially, the `haddock` of the `Web.Hyperbole` module helps me a lot to understand the motivation, architecture and design about `hyperbole`. Now I think I can make some web apps with `hyperbole`.

**Comment by seanhess** [comment]
Glad to hear that! I would hope so, given that it wasn't even released when you opened this. Still not sure how you even found the repo :)

Thanks for inspiring me to do the full release! https://www.reddit.com/r/haskell/comments/1cxh7wg/ann_hyperbole_interactive_html_applications_with/
