### ISSUE TITLE
Triggering action for different hyperview

### ISSUE THREAD

**Issue by cgeorgii** [seanhess/hyperbole#15]
Hello! While playing with the contacts example, I added a form to the page to add a new contact:
![image](https://github.com/user-attachments/assets/d5cb1a93-a4e2-40d4-af56-5dac8e027831)

When this new contact form is submitted, I would like the list of contacts to be automatically reloaded. Is emitting an action from a handler function supported by `hyperbole`? Or is there another more idiomatic way to achieve the same effect?

Thanks!

**Comment by seanhess** [comment]
Great question! Is your form a separate HyperView? Or is inside `Contacts`?

If it's part of the `Contacts` HyperView, this can be done by copying the functionality from the `Reload (Maybe Filter)` action. Let's say you've added a new action `AddUser`, as shown below:

```
data ContactsAction
  = Reload (Maybe Filter)
  | Delete Int
  -- My new action
  | AddUser 
  deriving (Show, Read, ViewAction)
  
contacts :: (Hyperbole :> es, Users :> es, Debug :> es) => Contacts -> ContactsAction -> Eff es (View Contacts ())
contacts _ (Reload mf) = do
  us <- usersAll
  pure $ allContactsView mf us
contacts _ (Delete uid) = do
  userDelete uid
  us <- usersAll
  pure $ allContactsView Nothing us
 contacts _ AddUser = do
  -- your custom code 
  readTheFormAndAddTheUser
  
  -- Same as Reload: we've already factored this functionality into easy functions
  us <- usersAll
  pure $ allContactsView Nothing us
```

The principle here is to write view functions that render the contents based on input data. So if your input data change, it's as simple as using the same function to generate the view with updated info.

**Comment by seanhess** [comment]
I just updated [the contacts example](https://github.com/seanhess/hyperbole/blob/main/example/Example/Contacts.hs) to show how this could be done while reusing the form

**Comment by seanhess** [comment]
On the other hand, we need to do something different if the add user form is outside of the `Contacts` view for some reason (for example: if you only wanted to show it after they press a button, you could put it in its own HyperView).

Let's say you created a new HyperView called NewConcat for this:

```
data NewConcat = NewConcat
  deriving (Show, Read, ViewId)

data NewContactAction
  = OpenForm
  | AddContact
  deriving (Show, Read, ViewAction)
  
 instance HyperView NewContact where
  type Action NewContact = NewContactAction

newContact :: NewContact -> NewContactAction -> Eff es (View NewContact ())
newContact _ OpenForm = pure newContactFormView
newContact _ AddContact = do
  -- your custom code 
  readTheFormAndAddTheUser
  
  -- How do we reload the contacts here??
  
  pure closedContactFormView
```

We want to trigger Reload in the Contact view, right? We can do this using `target`. 

```
closedContactFormView :: View NewContact ()
closedContactFormView = do
  -- normally we can only trigger NewContactAction
  -- so this will give an error
  button (Reload Nothing) id "Reload"
  
  -- but if we use target, we can do it
  target Contacts $ do
    button (Reload Nothing) id "Reload"
```

But we don't want to make the user press a button for that to happen, so let's use lazy loading:

```
closedContactFormView :: View NewContact ()
closedContactFormView = do
  target Contacts $ onLoad (Reload Nothing) 0 (el_ "Reloading...")
  -- the rest of this view
```

And if `NewContact` was originally inside `Contacts`, that view will be replaced when it reloads

**Comment by seanhess** [comment]
I haven't thought deeply about allowing handlers to trigger other actions, but it's definitely doable. Needs to be part of a larger effort to enable server push

**Comment by cgeorgii** [comment]
> On the other hand, we need to do something different if the add user form is outside of the Contacts view for some reason

Yes, this was the case here. But your comment seems to imply that it would be better _not_ to have it outside, i.e. have it as a child of the `Contacts` page?

> But we don't want to make the user press a button for that to happen, so let's use lazy loading:
> 
> ```hs
> closedContactFormView :: View NewContact ()
> closedContactFormView = do
>   target Contacts $ onLoad (Reload Nothing) 0 (el_ "Reloading...")
>   -- the rest of this view
> ```
> And if NewContact was originally inside Contacts, that view will be replaced when it reloads


This is pretty much the solution I found but it feels a bit unsatisfying. It requires a full round-trip and requires this extra view. I'd much rather have a mechanism to trigger it in the backend and have an update to the view be pushed.


> I haven't thought deeply about allowing handlers to trigger other actions, but it's definitely doable. Needs to be part of a larger effort to enable server push

I'm not sure how straightforward that would be. After looking a bit into it, it seems that with the socket interpreter it might not be too complicated (since I _think_ we could just send responses to the socket and that's it), but with the HTTP interpreter there would need to be a more complicated mechanism to allow for multiple views. Something like [out-of-band swaps](https://htmx.org/attributes/hx-swap-oob/) in `htmx`.

But I think it would add a lot of flexibility, what about you?

**Comment by seanhess** [comment]
When it comes to the developer API, I think we should conceptualize it as triggering another action. We can add a function to the `Hyperbole` effect, which would look something like this:

```
newContact :: NewContact -> NewContactAction -> Eff es (View NewContact ())
newContact _ OpenForm = pure newContactFormView
newContact _ AddContact = do
  -- your custom code 
  readTheFormAndAddTheUser
  
  -- Now we can send actions to other views
  -- What should this be named? Other options are: `action` or `sendAction`?
  trigger Contacts Reload 
  
  pure closedContactFormView
```

What do you think?

**Comment by cgeorgii** [comment]
> ```hs
> newContact :: NewContact -> NewContactAction -> Eff es (View NewContact ())
> newContact _ OpenForm = pure newContactFormView
> newContact _ AddContact = do
>   -- your custom code 
>   readTheFormAndAddTheUser
>   
>   -- Now we can send actions to other views
>   -- What should this be named? Other options are: `action` or `sendAction`?
>   trigger Contacts Reload 
>   
>   pure closedContactFormView
> ```

This is exactly the API I had in mind, down to the name (`trigger`)!

As for the HTTP client, I have not yet looked at the data we send in a response so I don't know enough to be helpful, I think. Is it JSON? If so, I imagined adding an extra field with extra updates, so the frontend resolves the main update first and then the extra ones. Does that make any sense?

**Comment by seanhess** [comment]
Awesome! it's open for development then if you want to take a crack at it. Or I'll get to it eventually. 

> As for the HTTP client, I have not yet looked at the data we send in a response so I don't know enough to be helpful, I think. Is it JSON? If so, I imagined adding an extra field with extra updates, so the frontend resolves the main update first and then the extra ones. Does that make any sense?

It's a custom protocol that's more human-readable than JSON. Since the majority of the response is HTML, it would need escaping and be hard to read in a JSON object. It looks like this:

```
|VIEW-ID|Counter
|SESSION|session=; SameSite=None; secure; path=/
<style type='text/css'>...</style>

<div class='col' id='Counter'>
    ....
</div>
```

It's easy to add new metadata: just add a new line with `|MYMETA|My Value` At a certain point it might make sense to change the meta to JSON, but I like how easy to read it is.

**Comment by seanhess** [comment]
Closing this until someone can come up with a motivating example for triggers that can’t be solved more simply using nested views
