### ISSUE TITLE
Create project

### ISSUE THREAD

**Issue by pegesund** [seanhess/hyperbole#26]
Hi, any canonical way on how to start building a new project, just by including the cabal-file, not copying the hole project?

**Comment by pegesund** [comment]
Never mind, it was too easy for a ticket :) Thanks for a cool solution!

**Comment by seanhess** [comment]
Glad you figured it out! If anyone sees this later, you create a new empty haskell project like any other. I use `cabal init` in an empty directory. Then add `hyperbole` to the dependencies and paste in the basic example from the readme. From there, you can start adding more interactivity, a database of your choice, or a router with more pages, etc
