### ISSUE TITLE
Missing "client/dist/hyperbole.js" when trying to build & run the examples

### ISSUE THREAD

**Issue by cloudyluna** [seanhess/hyperbole#3]
Hello! Thx for making the library.

I cloned the repo to try run the examples, but I'm hitting a build error here -

Build log:
```
$ cd hyperbole
$ cabal run
Build profile: -w ghc-9.6.5 -O1
In order, the following will be built (use -v for more details):
- hyperbole-0.3.6 (lib) (first run)
- hyperbole-0.3.6 (exe:examples) (first run)
Preprocessing library for hyperbole-0.3.6..
Building library for hyperbole-0.3.6..
[ 2 of 10] Compiling Web.Hyperbole.Embed ( src/Web/Hyperbole/Embed.hs, /home/cloudyluna/workspace/haskell/archives/hyperbole/dist-newstyle/build/x86_64-linux/ghc-9.6.5/hyperbole-0.3.6/build/Web/Hyperbole/Embed.o, /home/cloudyluna/workspace/haskell/archives/hyperbole/dist-newstyle/build/x86_64-linux/ghc-9.6.5/hyperbole-0.3.6/build/Web/Hyperbole/Embed.dyn_o )

src/Web/Hyperbole/Embed.hs:16:15: error: [GHC-87897]
• Exception when trying to run compile-time code:
client/dist/hyperbole.js: withBinaryFile: does not exist (No such file or directory)
Code: (embedFile "client/dist/hyperbole.js")
• In the untyped splice: $(embedFile "client/dist/hyperbole.js")
|
16 | scriptEmbed = $(embedFile "client/dist/hyperbole.js")
|               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: cabal: Failed to build hyperbole-0.3.6 (which is required by
exe:examples from hyperbole-0.3.6)
```
git commit: [e6d4118](https://github.com/seanhess/hyperbole/commit/e6d4118069a276cc16d5d66ce6ba1e7a686ca3f6)

Do I need to get `hyperbole.js` from somewhere first?

**Comment by seanhess** [comment]
Uh oh. Looks like the js file was in the .gitignore.  It’s distributed on
hackage correctly so if you put hyperbole as a dependency in a new project
it should work correctly. Then you could copy in the examples (and add its
dependencies) and run them that way. It’s probably more hassle than it’s
worth to build the js

So sorry about that. I didn’t test a fresh checkout. I’m away from my
computer for 2 weeks, I can fix when I get back. Let me know if the above
workaround works for you! If not we can figure something else out

**Comment by hughjfchen** [comment]
I met that too. What I've done is to download the tarball from hackage, extract the `hyperbole.js` file and put it under the right directory and then everything works.

**Comment by seanhess** [comment]
Thanks for posting that solution @hughjfchen 

An alternative workaround is to build the JS: 
1. Install NPM - “brew install node” on Mac, I think. 
2. Cd to the repo
3. Run “npm install”
4. Run “npx webpack”
5. “Cabal run”

**Comment by cloudyluna** [comment]
@hughjfchen Thank you! Using the `hyperbole.js` bundled in the tarball uploaded to Hackage works! 

@seanhess 
> Thanks for posting that solution @hughjfchen
> 
> An alternative workaround is to build the JS:
> 
>     1. Install NPM - “brew install node” on Mac, I think.
> 
>     2. Cd to the repo
> 
>     3. Run “npm install”
> 
>     4. Run “npx webpack”
> 
>     5. “Cabal run”

Thanks! I tried `npm install`ing in the repo root, but it says `package.json` is missing though there is a `package-lock.json` lying around in this directory. Doing this in `hyperbole/client` worked instead but I hit Typescript compile error for some reason.

```
cloudyluna@suse:~/workspace/haskell/archives> cd hyperbole
cloudyluna@suse:~/workspace/haskell/archives/hyperbole> npm install
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /home/cloudyluna/workspace/haskell/archives/hyperbole/package.json
npm ERR! errno -2
npm ERR! enoent Could not read package.json: Error: ENOENT: no such file or directory, open '/home/cloudyluna/workspace/haskell/archives/hyperbole/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in: /home/cloudyluna/.npm/_logs/2024-05-25T13_15_47_849Z-debug-0.log
cloudyluna@suse:~/workspace/haskell/archives/hyperbole> cd client/
cloudyluna@suse:~/workspace/haskell/archives/hyperbole/client> npm install
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated coffee-script@1.3.3: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)

added 201 packages, and audited 202 packages in 7s

19 packages are looking for funding
  run `npm fund` for details

21 vulnerabilities (1 low, 1 moderate, 11 high, 8 critical)

To address issues that do not require attention, run:
  npm audit fix

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
cloudyluna@suse:~/workspace/haskell/archives/hyperbole/client> npx webpack
asset hyperbole.js 43 KiB [emitted] (name: main)
runtime modules 670 bytes 3 modules
modules by path ./src/*.ts 22.3 KiB
  ./src/index.ts 10.3 KiB [built] [code generated]
  ./src/sockets.ts 8.04 KiB [built] [code generated]
  ./src/events.ts 3.01 KiB [built] [code generated] [1 error]
  ./src/action.ts 544 bytes [built] [code generated]
  ./src/lib.ts 467 bytes [built] [code generated]
./node_modules/omdomdom/lib/omdomdom.es.js 12.1 KiB [built] [code generated]

ERROR in /home/cloudyluna/workspace/haskell/archives/hyperbole/client/src/events.ts
./src/events.ts 57:1-2
[tsl] ERROR in /home/cloudyluna/workspace/haskell/archives/hyperbole/client/src/events.ts(57,2)
      TS1128: Declaration or statement expected.
ts-loader-default_e3b0c44298fc1c14
 @ ./src/index.ts 39:0-103 151:20-30 178:4-22 187:4-14 188:4-15 197:4-20 206:4-16

webpack 5.89.0 compiled with 1 error in 3695 ms
cloudyluna@suse:~/workspace/haskell/archives/hyperbole/client> ls -a dist/
.  ..  hyperbole.js
```

**Comment by seanhess** [comment]
Let’s call pulling the js from the tarball the official workaround for now
then. I’ll get it fixed in a couple weeks and also add directions to build
the js.

**Comment by pherk** [comment]
event.ts line 57: superfluous parenthesis

**Comment by seanhess** [comment]
Fixed: I added JS build instructions to the README: https://github.com/seanhess/hyperbole?#local-development. Tested on a fresh checkout. 

Thanks for the catch on the TS compile @pherk

**Comment by kfigiela** [comment]
Dev setup for local development is great, but can we consider adding `client/dist/hyperbole.js` to the repo? To be pragmatic – this really helps prototyping/fixing bugs in a real world environments – you just point to the repo in stack.yaml or your nix setup to the patched version and it will build everywhere (local, other developers, CI, etc.).

**Comment by seanhess** [comment]
Yeah, you're right. The real benefit of being able to build immediately outweighs the possible inconvenience of merge conflicts. Just pushed the changes to include it.
