### ISSUE TITLE
Use mode:"production" to build hyperbole.js included in haskell sdist?

### ISSUE THREAD

**Issue by jhrcek** [seanhess/hyperbole#35]
While browsing the sources I noticed that you're including development build of hyperbole.js in the hackage source distribution.

It might be better to use `mode: "production"` as recommended here: https://github.com/seanhess/hyperbole/blob/37091269b0fc081f53ed5ce752e57db3dcbd7430/client/dist/hyperbole.js#L7

(At least for when releasing the next version to hackage)

**Comment by seanhess** [comment]
Maybe we should add a script: `bin/sdist` (or something) that runs webpack with a flag to override this and package everything. Definitely feel free to take a crack at a PR if you want!

**Comment by jhrcek** [comment]
If I was to add a script for this, it would look like this:
```bash
#!/usr/bin/env bash
pushd client
npm instal
npx webpack --mode=production
popd
cabal sdist
```
What's slightly annoying is that after you run it, it modifies a bunch of files that are checked in the repository, so you have to check them out. But then you could just set the mode to production in webpack config by default and check the production js build in the repo, which would be easier.

The differences between prod and dev. build: smaller size (20k vs 52k), no warnings about dev mode being used (looks "unproffesional" in hackage distro), but less readability when debugging in browser dev. console (but you could always build with dev mode to troubleshoot :smile: )
