### ISSUE TITLE
can you trigger actions from the server side?

### ISSUE THREAD

**Issue by mwotton** [seanhess/hyperbole#36]
Is there a way for the server to trigger changes in response to something happening serverside, given that you've got the websocket open already? or is the model here to continually poll until something changes?

**Comment by seanhess** [comment]
Could you help me understand your use case? Is it similar to #15? Or do you mean you want some other thread to be able to push updates to a view, like a chat server?

**Comment by mwotton** [comment]
more like a chat server - in my specific use case, i have a streaming api that produces solutions to a problem that get increasingly accurate, and i'd like to render them as they are produced, allowing the user to pause or kill the solver when it's deemed good enough.

**Comment by seanhess** [comment]
The server is stateless: it doesn't know who any of the clients are so doesn't have a way to direct anonymous information to a specific one. Implementing true push would require identifying clients and managing some state for them. It would also require splitting the capabilities between the HTTP server and the WebSocket one. 

But this is really easy to implement with polling: `onLoad 1000 Reload $ el_ "Refreshes every second"` - If the action is expensive, long-running, or needs something that's already in another thread, you can use any of the normal ways to communicate between threads: a database, STM, etc.
