### ISSUE TITLE
Feature Request / Cookbook Entry request // button action to trigger multiple view updates

### ISSUE THREAD

**Issue by benjaminweb** [seanhess/hyperbole#39]
**Common pattern** I've encountered is one button click should trigger update of multiple views.
Button targets implicitly.
**Workaround**: I currently solve this by nesting the second action view under the first triggered one.
Limitation: However if triggers might originate from different views, this would not be practical.

**_How can I update two or more  independent views with one button action at once (chaining or in parallel)?_**

…or am I solving the wrong problem?

**Comment by seanhess** [comment]
See #15

But this might be easily solvable by triggering an action on a parent view. Can you give me a specific example?

**Comment by benjaminweb** [comment]
I am afraid, currently I am not able to. Here is how far I get it:

```haskell
{-# LANGUAGE DeriveAnyClass #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE TypeFamilies #-}
{-# OPTIONS_GHC -Wno-missing-signatures #-}

module Suppz.Web.UpdateMultipleViews where

import Data.Text (Text)
import Web.Hyperbole

data Parent = Parent Int
  deriving (Show, Read, ViewId)

data ParentAction = Louder Text
  deriving (Show, Read, ViewAction)

instance HyperView Parent where
  type Action Parent = ParentAction
  type Require Parent = '[Sidebar]

message :: Parent -> ParentAction -> Eff es (View Parent ())
message _ (Louder m) = do
  -- side effects
  let new = m <> "!"
  pure $ parentView new

--umbrella :: View Parent ()
umbrella = do
          hyper (Parent 1) $ parentView "Hello"
          hyper (Parent 2) $ parentView "World!"

parentPage :: (Hyperbole :> es) => Page es '[Parent, Sidebar]
parentPage = do
  -- message listens for any actions that the messageView triggers
  handle message $ handle sidebar $ load $ do
    pure $ do
      el bold "Message Page"
      row (gap 20 . pad 20) $ do
        col (pad 20 . border 1) $ 
          hyper (Sidebar 1) $ sidebarView "sidebar 1 stuff"
        col (pad 20 . border 1) $ umbrella
        col (pad 20 . border 1) $ 
          hyper (Sidebar 2) $ sidebarView "sidebar 2 stuff"

parentView :: Text -> View Parent ()
parentView t = do
  el_ $ text t
  button (Louder t) id "Change Message"
  -- and simultaneously send `SetSidebarText t` to view `Sidebar 1`
  -- and another `SetSidebarText t` to view `Sidebar 2`
  -- without loosing state of `umbrella` => I can't just reload parentPage 

data Sidebar = Sidebar Int
  deriving (Show, Read, ViewId)

data SidebarAction = SetSidebarText Text
  deriving (Show, Read, ViewAction)

instance HyperView Sidebar where
  type Action Sidebar = SidebarAction

sidebar :: Sidebar -> SidebarAction -> Eff es (View Sidebar ())
sidebar _ (SetSidebarText t) = pure $ sidebarView t

sidebarView :: Text -> View Sidebar ()
sidebarView t = el bold $ text t
```

**Comment by seanhess** [comment]
Thanks for sending that! I assume that you're using lazy loading and extra hyper views just to try things out, but your example can be greatly simplified by getting rid of the presets and results view:

https://gist.github.com/seanhess/37355f9b5b02adae335fd7c8cdc42b29

Take note that you can create _view functions_, which accept different parameters for rendering, without making them HyperViews. They are all `View Central ()`, but you can pass a bunch of different state parameters into them to control the. page. 

HyperViews are intended to update more independently. So the simple answer to this is to use larger views. Use functions for code reuse. Only reach for a HyperView if you need it to update independently, or that paradigm makes it easy. 

Closing for now, but feel free to respond with further thoughts or clarifications. We can reopen if we can discover a motivating example

**Comment by seanhess** [comment]
Also, if I understand what you were going for, it would be solveable with #15

**Comment by benjaminweb** [comment]
Yup, it was simply a setup / example for #15.

Key takeaways:
- I can create multiple functions with same return type like `View Central ()` with different input types and can combine them together freely to enhance code reuse; can’t be updated independently
- only hyperviews can be updated independently but are not variable in input arguments, correct?

What do you mean with larger views specifically?

**Comment by seanhess** [comment]
> I can create multiple functions with same return type like View Central () with different input types and can combine them together freely to enhance code reuse; can’t be updated independently

Yep!

> only hyperviews can be updated independently but are not variable in input arguments, correct?

I'm not 100% sure what you mean by "variable in input arguments", but this probably isn't correct. You can add arguments to the main view function, like any haskell function. You can also pass arguments to handlers from the top-level page. See https://github.com/seanhess/hyperbole/blob/main/example/Example/Counter.hs for an example. 

By larger views, I mean, putting more things into a single hyperview. It's tempted to make everything into a "component" if you've done web development before, but you're going to have an easier time if you try to use plain old function arguments first, and only use independent hyperviews only when you need things to update independetly. 

You can push the funciton arguments technique pretty far. You can even create view functions that expect an action as an argument. 

Something like:

```
chooseOne :: Action id -> Action id -> View id ()
chooseOne onChooseA onChooseB = do
  el_ "Choose One"
  button onChooseA id "A" 
  button onChooseB id "B"
```

That's a silly example, but hopefully you get the idea.
