### ISSUE TITLE
Add TodoMVC example

### ISSUE THREAD

**Issue by benjaminweb** [seanhess/hyperbole#45]

**Comment by seanhess** [comment]
@benjaminweb I added this! See Example.Todo

**Comment by benjaminweb** [comment]
I've tried to reconstruct the architecture of your TodoMVC implementation:
![Untitled-2024-11-14-1102](https://github.com/user-attachments/assets/af04a17b-3ed0-491f-bd0e-69b622f36f25)
(I've also put some questions on the [commit](https://github.com/seanhess/hyperbole/commit/c8e031cf042f699a616fea95f0c4f44c05d00c9a) that implements TodoMVC. I appreciate your answers to those. I could add them afterwards as doc strings into the implementation.

**Comment by seanhess** [comment]
Oh, it sounds like it might help to read:

https://hackage.haskell.org/package/effectful-core-2.5.1.0/docs/Effectful-Dispatch-Dynamic.html

**Comment by seanhess** [comment]
@benjaminweb can you review the new documentation? Let me know if you think it answers most of your questions or not:

https://hackage.haskell.org/package/hyperbole-0.4.2/candidate/docs/Web-Hyperbole.html

**Comment by benjaminweb** [comment]
Insights:
- Components might be more important than HyperViews (for code architecture)
- Yet their semantic appears to be more complicated => how can this be simplified?

What I don’t get (fully):
- Why do I need effects for Todos? because they alter the session content, which is a state external to 

_You partially skip Views and to jump into HyperViews, then to come back to View Functions. Wouldn’t it be more straightforward to grow a View into View Function? …and from that to a HyperView?_

- - -

Let me mirror back how I understand your docs currently:


Page:
- A way of defining what data is loaded on initial page load (outermost Monad) and then defining what is visually on the page (innermost view Monad); it may contain some HyperViews which update.
- A page is constructed by one or more Views (matching those in the rectangular brackets).
- A Page might have side effects, therefore: Eff es (Page …).

View Functions = Components:
- Without parameters: factored out some part of page => ViewId
- A ViewId distinguishes different sections of the page, potentially multiple of the same type.
- With parameters: Some views should be dynamic, they should take and reflect different input data, basically: “give me some input and I’ll create a individual view for you.”

- Now our page consists of sections that are generated by view functions; the views are different depending on the input we provide to the functions.
- Our page could be generated on load with different data from the server now
- As of now there’s no possibility to let the site change based on the user’s interaction.

HyperViews:
- What we do want is defining different types of Actions to identify what the user wants to be done.
- Then, we need to specify what needs to be done with the site for the different Actions.
- We discriminate the different Actions by defining the HyperView type instance for the View and specify what needs to be done for each in the update function.
- That means that the Actions are only possible within the bounds of the HyperView.
- Simply put, the update function rebuilds our view with different input data, that is now changed by the user.
- Before our page could load with different data from the server, now we can identify different types of actions triggered by the user and update sections (HyperViews) of our independently (by rebuilding their views using different inputs).
- Each HyperView has a list (an ADT) of actions that are possible to trigger from it. Any of these will trigger an update and replace its contents.

Extending Actions to knowing the state used on generating the View:
- Now, our (Hyper)View doesn’t carry the input data it has been constructed with. That means it’s stateless.
- At times, we might want our Action we trigger to consider the state the View has been built with last time. For example, a counter. If our counter stands at 3, we want the Action Increment to know the state of the counter. Why? So it can increment 3 by 1 to result 4 and generate the new view with input value 4. 
    - For carrying a state within a view (for an action), we extend the Action with an argument.

Loading data, carrying state globally, etc.:
- We are now able to build views that carry a value of their state when they’ve been generated in their Actions.
- We’ve learned that Actions are limited to their matching View (they are defined in their HyperView). That means, we cannot carry a global state for our whole page.
- So, we need something that breaks out of this limitation (and is able to break in again). We call that side-effects. Anything that breaks out of the context of a HyperView is a side-effect.
- How do we upgrade a HyperView to allow breaking out and breaking in for specific kinds of Effects?
- We constrain the HyperView by the type of the Effect we want to allow.
- Then, we wrap the full page in a handler function that takes the effects emitted from within any part of the page. The handler function then makes sure that the Effects are handled.
- We discriminate the variants of our specific Effect type (similar to Actions of a HyperView) and define their actions as functions.
- The wrapper function around the page waits for any Effect of that type to break out of our Page (which allows only specified to do so) and handles it by calling the corresponding function.
- What are the advantages of that?

How to use HyperViews:
- Re-using HyperViews // Shouldn’t it be default to make each HyperView distinct?
    - We’ve learned that HyperViews are sections of our page that update independently of the other parts.
    - Let’s use the same HyperView twice. Test it.
    - Weird. When an action is triggered from one, it goes to both.
    - It appears that the action does not know to which HyperView it needs to fly to.
    - But once we allow the Views to be distinguished, the action of a HyperView will now its correct target View.
- Requirement: Loading a Section and a Subsection of it independently // Nesting HyperViews
    - we now can create a section of a page that updates independently from the other sections.
    - but at times, we might require only a subsection of that section to update independently — while still being able to update the full section independently.
    - for this, we can use HyperViews in HyperViews.
    - For this to work, the parent HyperView needs to know what to do when a child HyperView happens. We tell it how by requiring it the child HyperView in its instance definition Require.
    - Whenever an action of a child happens, it knows where to direct that towards. So only the correct child gets updated.
    - And still we can independently reload the parent HyperView as we like.
How NOT to use HyperViews:
- As you’ve might have experienced, you will likely reuse design components across the page, so across any number of different HyperViews.
- That works fine until your component has some action.
- Why? We know that by design we can only use Actions within the HyperView they are defined in.
- So, any component with an action for a different HyperView needs to be a different one.
- That means as it stands now we can’t reuse components with Actions across different HyperViews. Too bad.
- Still, if we try hard to reuse components across different sections, we might fall prey to create a global HyperView. We would design our HyperViews FOR the need to be able to reuse our components. And not along the requirements which sections of our page need to update independently. As a result our design will have high coupling and frustratingly hard to maintain.
- What do we want?
    - Update specific subsections of a page independently.
    - Re-use components (with actions) across different HyperViews.
- What don’t we want?
    - To abuse HyperViews for enabling re-use of components.
- When we try to abuse HyperViews for reusing components with actions, we assume the components contain the action already.
- If we factor the action out, meaning our components is abstract of an action. That means we can use the component in any HyperView and provide it in place the action fitting the HyperView.
- By defining action-abstract components, we can re-use them across any HyperView. This is the key to let your code compose well.

Pages:
- routes urls to pages.

Anti-patterns:
- create super-generic HyperView: leads to inheretence-like designs that don’t compose well => Don’t leverage HyperViews for code reuse! RATHER: think about which subsections of a page ought to update independently: Those are HyperViews. Everything else that is being reused, is a Component. Period.

**Comment by benjaminweb** [comment]
Worked through all your responses. Thanks for those!
Not yet touched upon the Effectful doc. Would that be required reading for any user of Hyperbole? If not, when would I need to dive into it?

Yes, to me personally stopping to abuse HyperViews to reuse components with hard-coded actions saves the day. If anything, this determines most how I can and will structure my code. But let’s see which experience I gain.
