### ISSUE TITLE
Web socket messages processed out of order

### ISSUE THREAD

**Issue by kfigiela** [seanhess/hyperbole#5]
Hey! I've been playing around with hyperbole for last couple of days. In my use-case, I have two hyper views polling similar to the example in https://github.com/seanhess/hyperbole/blob/main/example/Example/LazyLoading.hs. 

In client code in https://github.com/seanhess/hyperbole/blob/748444e8bfe68273fbb922f19a1674fc2b4a5176/client/src/sockets.ts#L78
the request is sent and it awaits the response, which is the first incoming message on the websocket. However, in case of multiple parallel requests, responses may be returned out-of-order. This causes one hyper view to be replaced with the contents of the other. 

Probably, there should be some request id that is returned by the response, so appropriate event handler is called on JS side.

Alternatively, the response could indicate what hyper view needs to be updated making this fully asynchronous. That'd open a possibility for server initiated push.

**Comment by seanhess** [comment]
Hey, thanks for submitting this! This has been in the back of my mind for a
while.

The requests are targeted to a particular hyperview, so a simple solution
for this would be to have the response return the view id, and look up the
correct view in the response: make the request and the response
independent.

But that wouldn’t prevent errors if the client triggers another update
within the same view while a request is in flight: like if someone
double-clicks a submit button, or clicks a button while polling. These
could be prevented using onRequest, but it needs better default behavior.

For that we would need a request id. What’s the correct logic for out of
order responses? Just apply them in order? Only render the latest?

What are other ways that requests could overlap and mess things up?

**Comment by kfigiela** [comment]
I did some experimentation and opened a [draft PR](https://github.com/seanhess/hyperbole/pull/6) to help with the discussion. By adding a correlation id, I was able to resolve the issue of updating incorrect hyperview. 

Out of order arrival of responses for the same hyper view was not an issue at the moment. Websocket connection was processed single-threaded, so the messages were processed sequentially on backend. This did not apply to HTTP fallback though, which would be processed multi-threaded and could be an issue. 

I did small refactor of how web sockets are handled in the backend and that added concurrency there which should improve UI responsiveness in case there are long responses. This still needs more work (e.g. to kill asyncs when connection is gone, etc.), but overall works. Since out-of-order responses are a thing now, I added a check on response processing to prevent rendering response if the target has been already updated by later request.

There is still yet another race condition related to handling `onLoad` – basically, while the old contents is removed/update, the timeout (triggering further request) is not. I tried adding that and you can see that on a branch, but this did not fully fixed the issue – needs more investigation.

**Comment by seanhess** [comment]
Awesome, thanks for working on this. I’m back from my trip in a few days,
I’ll take a close look on Monday!

**Comment by seanhess** [comment]
This is a great start! I like what you're doing with the correlation id. I left you a few specific questions in the PR, but this will be a good place to start from. 

I'd like to start by creating some test cases to reproduce errors. Let's start by completely implementing a solution to your original issue, then move on to implementing the concurrent socket handler. Does LazyLoadingRace reproduce the original issue or does it only apply once the socket handlers are multi-threaded?

I'll start playing with it. Thanks again!

**Comment by seanhess** [comment]
Minimal reproducing example. Working in [concurrent branch](https://github.com/seanhess/hyperbole/tree/concurrent)

```
module Example.Concurrent where

import Data.Text (pack)
import Effectful
import Example.Effects.Debug
import Web.Hyperbole


page :: (Hyperbole :> es, Debug :> es, IOE :> es) => Page es Response
page = do
  handle content

  load $ do
    pure $ do
      col (pad 20) $ do
        hyper (Contents 1000) $ viewPoll 1
        hyper (Contents 2000) $ viewPoll 100


data Contents = Contents Milliseconds
  deriving (Generic, Param)
instance HyperView Contents where
  type Action Contents = ContentsAction


data ContentsAction
  = Load Int
  deriving (Generic, Param)


content :: (Hyperbole :> es, Debug :> es, IOE :> es) => Contents -> ContentsAction -> Eff es (View Contents ())
content (Contents dl) (Load n) = do
  delay dl
  pure $ viewPoll (n + 1)


viewPoll :: Int -> View Contents ()
viewPoll n = do
  onLoad (Load n) 0 $ do
    row (gap 10) $ do
      el_ "Polling:"
      text $ pack (show n)
```

**Comment by seanhess** [comment]
In the [concurrent branch](https://github.com/seanhess/hyperbole/tree/concurrent), responses are now returning the view-id, and sockets are successfully ignoring responses for other views. 

I immediately ran into the single-threaded issue as you described, using the same small page: Example.Concurrent

**Comment by seanhess** [comment]
In the [concurrent branch](https://github.com/seanhess/hyperbole/tree/concurrent), responses are now returning the view-id, and sockets are successfully ignoring responses for other views. 

I immediately ran into the single-threaded issue as you described, using the same small page: Example.Concurrent

**Comment by kfigiela** [comment]
Thanks! Let me know when it's the right moment to review and test.

**Comment by seanhess** [comment]
Give it a look now. Let's merge a fix for the out-of-order problem and leave the single-threaded problem for later. It'll require a more in-depth fix. This PR should correctly update views, even if the server handles long-running requests sequentially

**Comment by kfigiela** [comment]
Will review tomorrow

**Comment by seanhess** [comment]
Closing. Feel free to open a new issue for web socket parallelism
