### ISSUE TITLE
setSession putting empty value while using redirect

### ISSUE THREAD

**Issue by tusharad** [seanhess/hyperbole#52]
Hi team,

I'm currently using commit 8633d7df648facaae32ac3b08e8f9bafbd56cfe8 from December 3rd. I've encountered an issue with session handling in the following context:

```haskell
instance (IOE :> es, Hyperbole :> es) => HyperView FormView es where
  data Action FormView
    = Submit
    deriving (Show, Read, ViewAction)
    
  handle Submit = do
    setSession "x" ("y" :: Text)
    redirect "/"
 ```
 
When I execute the above code, the session key is added to the cookies as expected, but the value is empty. Here's a screenshot of the behavior:
 
 
![image](https://github.com/user-attachments/assets/b06ceb6d-34d3-471c-a042-a75088fb3d3c)

However, if I replace the redirect call with a direct view rendering instead, everything works as expected, and the session value is properly set. 
Could you please help investigate this issue? Let me know if additional details are required.

Thank you!

**Comment by seanhess** [comment]
Good catch! Fixed in main
